language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - MPI_IMPL=mpich
  #- MPI_IMPL=openmpi
before_install:
  - sh ./travis/install-deps.sh $MPI_IMPL
script:
  - sh ./travis/build-run.sh
after_failure:
  - cat ./config.log
  - head -n100 ./test/*.log
